# docker-compose.yaml (Airbyte + MinIO) — resilient & 2GB-VM friendly
# Notes:
# - Remove any "version:" key (Compose v2 ignores it).
# - Assumes a .env with:
#     POSTGRES_USER=airbyte
#     POSTGRES_PASSWORD=airbyte
#     POSTGRES_DB=airbyte
#     MINIO_ROOT_USER=minioadmin
#     MINIO_ROOT_PASSWORD=minioadmin
#     INTERNAL_API_HOST=airbyte-server:8000   # optional but recommended

services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: minio
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    volumes:
      - ./volumes/minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks: [data_net]

  airbyte-db:
    image: airbyte/db:0.58.0
    container_name: airbyte-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # PGDATA not needed because we mount the default path directly
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [data_net]

  airbyte-server:
    image: airbyte/server:0.58.0
    container_name: airbyte-server
    depends_on:
      airbyte-db:
        condition: service_healthy
    environment:
      # ---- Primary DB (covering variants across releases) ----
      DATABASE_HOST: airbyte-db
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_DB: ${POSTGRES_DB}

      AIRBYTE_DATABASE_HOST: airbyte-db
      AIRBYTE_DATABASE_PORT: 5432
      AIRBYTE_DATABASE_USER: ${POSTGRES_USER}
      AIRBYTE_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      AIRBYTE_DATABASE_DB: ${POSTGRES_DB}

      CONFIG_DATABASE_HOST: airbyte-db
      CONFIG_DATABASE_PORT: 5432
      CONFIG_DATABASE_USER: ${POSTGRES_USER}
      CONFIG_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      CONFIG_DATABASE_DB: ${POSTGRES_DB}

      JOB_DATABASE_HOST: airbyte-db
      JOB_DATABASE_PORT: 5432
      JOB_DATABASE_USER: ${POSTGRES_USER}
      JOB_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      JOB_DATABASE_DB: ${POSTGRES_DB}

      RUN_DATABASE_MIGRATION_ON_STARTUP: "true"
      # Keep heap modest for a 2 GB droplet
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx768m"
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [data_net]

  airbyte-webapp:
    image: airbyte/webapp:0.58.0
    container_name: airbyte-webapp
    depends_on:
      airbyte-server:
        condition: service_healthy
    environment:
      # Ensure the UI calls the right server address
      INTERNAL_API_HOST: ${INTERNAL_API_HOST:-airbyte-server:8000}
    ports:
      - "8001:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [data_net]

  airbyte-worker:
    image: airbyte/worker:0.58.0
    container_name: airbyte-worker
    depends_on:
      airbyte-server:
        condition: service_healthy
    environment:
      DATABASE_HOST: airbyte-db
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_DB: ${POSTGRES_DB}

      CONFIG_DATABASE_HOST: airbyte-db
      CONFIG_DATABASE_PORT: 5432
      CONFIG_DATABASE_USER: ${POSTGRES_USER}
      CONFIG_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      CONFIG_DATABASE_DB: ${POSTGRES_DB}

      JOB_DATABASE_HOST: airbyte-db
      JOB_DATABASE_PORT: 5432
      JOB_DATABASE_USER: ${POSTGRES_USER}
      JOB_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      JOB_DATABASE_DB: ${POSTGRES_DB}

      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    restart: unless-stopped
    networks: [data_net]

  airbyte-cron:
    image: airbyte/cron:0.58.0
    container_name: airbyte-cron
    depends_on:
      airbyte-server:
        condition: service_healthy
    environment:
      DATABASE_HOST: airbyte-db
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_DB: ${POSTGRES_DB}

      CONFIG_DATABASE_HOST: airbyte-db
      CONFIG_DATABASE_PORT: 5432
      CONFIG_DATABASE_USER: ${POSTGRES_USER}
      CONFIG_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      CONFIG_DATABASE_DB: ${POSTGRES_DB}

      JOB_DATABASE_HOST: airbyte-db
      JOB_DATABASE_PORT: 5432
      JOB_DATABASE_USER: ${POSTGRES_USER}
      JOB_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      JOB_DATABASE_DB: ${POSTGRES_DB}

      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    restart: unless-stopped
    networks: [data_net]

networks:
  data_net:
    driver: bridge
